### ISSUE TITLE
v2 SDK entry-point pulls in CLI-only deps (ora, chalk, cli-table3) at module load — breaks Node runtimes without them

### ISSUE THREAD

**Issue by akos-recart** [MagnivOrg/prompt-layer-js#203]
### Summary

Since v2.0.0, importing \`promptlayer\` from a plain Node service (no evals, no CLI) transitively loads a chain of CLI-only packages at module init. If any one of them is missing from \`node_modules\` — which can happen in slim runtime containers, in monorepos that dedupe transitives, or in bundled deploys that only bundle what code paths reference — the SDK fails to load with \`Cannot find module 'chalk'\` (or a sibling).

### Repro

\`\`\`ts
// nothing else needed
import { PromptLayer } from 'promptlayer'
\`\`\`

Runtime crash on the require of \`promptlayer/dist/index.js\`:

\`\`\`
Error: Cannot find module 'chalk'
    at Object.<anonymous> (/app/node_modules/promptlayer/dist/index.js:11:xx)
\`\`\`

We hit this after upgrading a Node 24 service from 1.3.5 → 2.0.15. Every pod crash-looped on startup for ~10 minutes until we reverted. The crash is not our SDK usage — it's the top-level \`require\` chain of \`dist/index.js\`.

### Root cause

Static import chain from the SDK entry point:

\`\`\`
src/index.ts
  → @/evaluations (index.ts)
    → EvalManager (manager.ts)
      → runEval (runner.ts)
        → @/evaluations/terminal
          → import ora, picocolors, cli-table3   (static, top-of-file)
\`\`\`

\`ora\` pulls in \`chalk\`, \`cli-cursor\`, \`cli-spinners\`, \`is-interactive\`, \`is-unicode-supported\`, \`log-symbols\`, \`stdin-discarder\`, \`string-width\` — all CLI concerns. Confirmed with \`grep -oE 'require\("[^\"]+\"\)' node_modules/promptlayer/dist/index.js\` on the compiled bundle.

None of the CLI deps are needed by the SDK's regular \`.run()\` / \`.templates.*\` / \`.tables.*\` paths — only by \`evaluate()\` (and the CLI).

### Proposed fix

Move all eval-terminal-tainted code behind a subpath export so the main entry stays lean:

- \`promptlayer\` — SDK, no CLI deps
- \`promptlayer/evaluations\` (or \`promptlayer/cli\`) — everything that needs \`ora\` / \`cli-table3\` / \`picocolors\`

Users who call \`evaluate()\` would import from the subpath. Everyone else — the vast majority of SDK consumers — gets a lean entry point.

Alternatives:

1. Lazy-\`require\` the CLI deps inside \`getTerminal()\` and the small handful of terminal API functions that need them. Smaller PR but keeps the module graph awkward.
2. Move \`getTerminal()\` and terminal-tainted \`runEval\` bits into a submodule that isn't statically re-exported by \`evaluations/index.ts\`.

Happy to open a PR for whichever approach you'd prefer. Given #1 is the smallest change and preserves the current public API, I'd lean that way if you want to keep the SDK single-entry.

### Environment

- Node 24.13.1 (also verified: crashes on Node 20 with the same missing module)
- \`promptlayer@2.0.15\`
- CJS consumer, no bundler in the deployment path (plain \`npm install\` in a slim container)

Thanks!
