### ISSUE TITLE
Addition of @google/genai causes error as promptlayer doesn't know about it

### ISSUE THREAD

**Issue by libbyschuknight** [MagnivOrg/prompt-layer-js#129]
Hello, we are using `promptlayer` and when we upgraded from 1.0.23 to 1.0.27 we started seeing exceptions when importing `promptlayer`.

Error:
```json
    "errorMessage": "Error: Cannot find module '@google/genai'\nRequire stack:\n- /var/task/node_modules/promptlayer/dist/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@google/genai'",
        "Require stack:",
        "- /var/task/node_modules/promptlayer/dist/index.js",
```

We got around this by adding `@google/genai`  to our own `package.json`.
We wanted to make sure you were aware of this issue. 

Thanks

**Comment by abubakarsohail** [comment]
Hi @libbyschuknight 

Thanks for reporting this. `@google/genai` is imported dynamically on runtime if required. Can you confirm if any of the prompts you are using have provider set to `google`?

**Comment by libbyschuknight** [comment]
Hey, so we do not use google for any prompts.
And given that we are getting errors when importing the index file, we're not sure the dynamic import is working.

We did a test by creating:

```js
// index.js
const promptLayer = require('promptlayer');

async function main() {
    try {
        // Example usage: log a prompt and get a response
        const prompt = "What is the capital of France?";
        const response = await promptLayer.ask(prompt);
        console.log("Prompt:", prompt);
        console.log("Response:", response);
    } catch (error) {
        console.error("Error:", error.message);
    }
}

main();
```

And

```json
// package.json
{
  "name": "prompt_layer_test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "promptlayer": "1.0.27"
  }
}
```

And we got this when running in the terminal:
```
npm start

> prompt_layer_test@1.0.0 start
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@google/genai'
Require stack:
- /Users/libby/work/prompt_layer_test/node_modules/promptlayer/dist/index.js
- /Users/libby/work/prompt_layer_test/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/libby/work/prompt_layer_test/node_modules/promptlayer/dist/index.js:1:2134)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/libby/work/prompt_layer_test/node_modules/promptlayer/dist/index.js',
    '/Users/libby/work/prompt_layer_test/index.js'
  ]
}
```

Hope that is useful. Libby

**Comment by hasaan21** [comment]
This should be resolved in  https://github.com/MagnivOrg/prompt-layer-js/releases/tag/v1.0.31

**Comment by pistell** [comment]
The issue still persists for me on v1.0.31

Even though I am not using Gemini I was able to solve it by `npm i @google/genai` 

Hopefully this will be fixed in the next patch

**Comment by hasaan21** [comment]
hi @pistell 

Can you please share more details on this so I can reproduce it on my end? and can you verify if you are using a prompt using gemini as your provider from promptlayer. If you are using a gemini related prompt. You will need to install @google/genai in your environment.
